"""update users, issues for nullable reporter

Revision ID: 1803a56e49c8
Revises: 6fc7f98cd5a0
Create Date: 2025-07-05 21:45:47.393002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1803a56e49c8'
down_revision: Union[str, Sequence[str], None] = '6fc7f98cd5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('issues_reporter_id_fkey'), 'issues', type_='foreignkey')
    op.create_foreign_key(None, 'issues', 'users', ['reporter_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.create_foreign_key(op.f('issues_reporter_id_fkey'), 'issues', 'users', ['reporter_id'], ['id'])
    # ### end Alembic commands ###
